version: '3.9'

services:
  messaging-service:
    build: .
    ports:
      - '5000: 5000'
      - '8800: 8800'
    networks:
      - webnet

networks:
  default:
    external: true
    name: gono-jobs-messaging-service
